FROM arm64v8/python:3.12-slim

COPY pip.conf /etc/pip.conf
COPY requirements.txt requirements.txt
# setuptools<81: APScheduler needs pkg_resources at runtime; python 3.12 stopped
# bundling setuptools and 81+ removed pkg_resources entirely
RUN python3 -m pip install --upgrade pip wheel "setuptools<81"
RUN python3 -m pip install -r requirements.txt

COPY . /probablefuturesbot
RUN cd /probablefuturesbot && python3 -m pip install .

WORKDIR /probablefuturesbot
