FROM arm64v8/python:3.12-slim

COPY pip.conf /etc/pip.conf
COPY requirements.txt requirements.txt
RUN python3 -m pip install --upgrade pip wheel setuptools
RUN python3 -m pip install -r requirements.txt

COPY . /probablefuturesbot
RUN cd /probablefuturesbot && python3 -m pip install .

WORKDIR /probablefuturesbot
