FROM arm64v8/python:3.8-buster

COPY pip.conf /etc/pip.conf
COPY requirements.txt requirements.txt
RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install -r requirements.txt

COPY . /probablefuturesbot
RUN cd /api-libraries/probablefutures-py && python3 -m pip install .
RUN cd /probablefuturesbot && python3 -m pip install .

WORKDIR /probablefuturesbot
